- name: Install Packages
  apt:
    update-cache=yes
    pkg={{ item }}
    state=present
  with_items:
    - python3-flask
    - python3-pip
    - python3-influxdb
    - npm

- name: Install Pythong modules using pip
  pip: name={{ item }} executable=pip3
  with_items:
    - python-crontab

- name: Install Angular
  npm:
    name=@angular/cli
    global=yes

- name: Enable Watchdog
  lineinfile: >-
    dest='/boot/config.txt'
    state=present
    line='{{ item }}'
  with_items:
    - dtparam=watchdog=on

- name: Setting Watchdog
  lineinfile: >-
    create=yes
    dest='/etc/modprobe.d/bcm2835-wdt.conf'
    state=present
    line='{{ item }}'
  with_items:
    - options bcm2835_wdt heartbeat=30

- name: Setting Heartbeat
  lineinfile: >-
    dest='/etc/systemd/system.conf'
    state=present
    line='{{ item }}'
  with_items:
    - RuntimeWatchdogSec=10

- name: Setting Mail Alias
  lineinfile: >-
    dest='/etc/aliases'
    state=present
    line='{{ item }}'
  with_items:
    - "root: root@dripper.green-rabbit.net"
  notify:
    newaliases

- name: Setting Heartbeat
  lineinfile: >-
    dest='/etc/systemd/system.conf'
    state=present
    line='{{ item }}'
  with_items:
    - RuntimeWatchdogSec=10

- name: Setting Exim4
  replace:
    path: /etc/exim4/update-exim4.conf.conf
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - regexp: dc_eximconfig_configtype='local'
      replace: dc_eximconfig_configtype='smarthost'
    - regexp: dc_smarthost=''
      replace: dc_smarthost='{{ smtp_host }}'
    - regexp: dc_local_interfaces='127.0.0.1 ; ::1'
      replace: dc_smarthost=dc_local_interfaces='127.0.0.1'
  notify:
    reaload exim4


# Local Variables:
# mode: yaml
# tab-width: 4
# End:
