# Raspberry Pi の初期設定をするレシピです。
#
# wpa_passphrase コマンドで生成した SSID および PSK の値を、
# 下記のフォーマットで wifi_config.yml という名前に保存することで、
# 無線 LAN の設定が行えます。
# ---------------
# wifi_config:
#   ssid: 「接続する SSID」
#   psk: 「接続する SSID の PSK」
# ---------------

- hosts: all
  vars_files: 
    - wifi_config.yml

  become: yes

  roles:
    - common
    - user

  pre_tasks:
    - name: Check ro-var_etc Enabled
      shell: mount -v | grep 'unionfs-fuse on /etc' warn=no
      register: readonly_etc
      failed_when: readonly_etc.rc not in [0, 1]

    - name: Check /etc_rw Existence
      stat: path=/etc_rw
      register: etc_rw

    - name: writable mount /etc
      when: readonly_etc.rc == 0 and etc_rw.stat.exists # read only active
      shell: rwmount

    # - name: Copy resolv.conf
    #   when: readonly_etc.rc == 0 and etc_rw.stat.exists # read only active
    #   copy: src=/etc_rw/resolv.conf dest=/etc/resolv.conf remote_src=yes

  post_tasks:
    - name: Sync /etc
      when: etc_rw.stat.exists
      shell: cporg
    
# Local Variables:
# mode: yaml
# tab-width: 4
# End:

