# Raspberry Pi の初期設定をするレシピです。
#
# wpa_passphrase コマンドで生成した SSID および PSK の値を、
# 下記のフォーマットで wifi_config.yml という名前に保存することで、
# 無線 LAN の設定が行えます。
# ---------------
# wifi_config:
#   ssid: 「接続する SSID」
#   psk: 「接続する SSID の PSK」
# ---------------


- hosts: all
  vars_prompt:
    - name: hostname
      prompt: "new hostname"
      default: "raspberrypi"
      private: no

  vars_files: 
    - wifi_config.yml

  become: yes

  roles:
    - common

  tasks:
    - name: Install Packages
      apt:
        update-cache=yes
        pkg={{ item }}
        state=present
      with_items:
        - emacs24-nox
        - tmux
        - git
        - zsh

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
