# Raspberry Pi の初期設定をするレシピです。
#
# wpa_passphrase コマンドで生成した SSID および PSK の値を、
# 下記のフォーマットで wifi_config.yml という名前に保存することで、
# 無線 LAN の設定が行えます。
# ---------------
# wifi_config:
#   ssid: 「接続する SSID」
#   psk: 「接続する SSID の PSK」
# ---------------

- hosts: all
  vars_files: 
    - wifi_config.yml

  become: yes

  roles:
    - common
    - user

# Local Variables:
# mode: yaml
# tab-width: 4
# End:

