- name: Install Packages
  apt:
    update-cache=yes
    pkg={{ item }}
    state=present
  with_items:
    - bluetooth
    - python-serial

# - name: Set Ruby2.1 default
#   shell: "{{ item }}"
#   with_items:
#     - update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby2.1 100
#     - update-alternatives --install /usr/bin/gem gem /usr/bin/gem2.1 200

# - name: Install Fluentd
#   gem:
#     name={{ item.name }}
#     version={{ item.version }}
#     user_install=False # NOTE: なぜか「no」ではない...
#   with_items:
#     - name: fluentd
#       version: 0.12.31

# - name: Copy Script
#   become: no
#   git:
#     repo=https://github.com/kimata/rasp-python.git
#     dest=~/rasp-python
#     force=yes
#     accept_hostkey=yes

# - name: Edit Fluentd Setting
#   become: no
#   replace: >-
#     dest='~/rasp-python/etc/fluent.conf'
#     regexp='{{ item.regexp }}'
#     replace='{{ item.replace }}'
#   with_items:
#     - regexp: 'command\s+python ".*$'
#       replace: 'command python "/home/{{ ansible_env["SUDO_USER"] }}/rasp-python/app/sense_env/sense_env.py"'
#     - regexp: 'host\s+".*$'
#       replace: 'host "{{ aggr_host }}"'

# - name: Setting Fluetd Autorun
#   lineinfile: >-
#     dest='/etc/rc.local'
#     state=present
#     insertbefore='exit 0'
#     line='fluentd -d /home/{{ ansible_env["SUDO_USER"] }}/rasp-python/etc/fluent.pid -c /home/{{ ansible_env["SUDO_USER"] }}/rasp-python/etc/fluent.conf -o /tmp/fluentd.log'

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
