- name: Install Packages
  apt:
    update-cache=yes
    pkg={{ item }}
    state=present
  with_items:
    - bluetooth
    - python-serial

- name: Disable internal Bluetooth
  lineinfile: >-
    dest='/boot/config.txt'
    state=present
    line='dtoverlay=pi3-disable-bt'
    
# Local Variables:
# mode: yaml
# tab-width: 4
# End:
